name: data_check
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pandas=2.3.2
  - scipy=1.10.1
  - pytest=7.4.0
  - numpy=1.26.4
  - scikit-learn=1.7.2
  - pip=24.3.1
  - pip:
      - mlflow==3.6.0
      - wandb==0.21.3
      - hydra-core==1.3.2
